<form action="<?php echo $this->getUrl('stumbata_submission/form/post') ?>" method="post">

	<ul class="form-list">
		<li>
			<label>Name: </label>
			<div class="input-box">
				<input type="text" name="Name" class="input-text"/>
			</div>
		</li>
		<li>
			<label>Phone: </label>
			<div class="input-box">
				<input type="text" name="Phone" class="input-text"/>
			</div>
		</li>
		<li>
			<label>Email: </label>
			<div class="input-box">
				<input type="email" name="Email" class="input-text"/>
			</div>
		</li>

	</ul>

    <button type="submit" class="button">Submit</button>
</form>