<?php

class SoftUni_KristinaKovacheva_Block_Adminhtml_KristinaKovacheva_Edit_Form
    extends Mage_Adminhtml_Block_Widget_Form
{
    public function __construct()
    {
        parent::__construct();
        $this->setId('submission_form');
        $this->setTitle(Mage::helper('SoftUni_KristinaKovacheva')->__('Submission Information'));
    }

    public function _prepareForm()
    {
        $model = Mage::registry('softuni_kristinakovacheva_kristinakovacheva');

        $form = new Varien_Data_Form(array(
            'id' => 'edit_form',
            'action' => $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('submission_id'))),
            'method' => 'post'
        ));

        $form->setHtmlIdPrefix('softuni_kristinakovacheva_kristinakovacheva_');

        $fieldset = $form->addFieldset('base_fieldset', array(
            'legend' => Mage::helper('SoftUni_KristinaKovacheva')->__('General information'),
            'class' => 'fieldset-wide'
        ));
        if($model->getId()){
            $fieldset->addField('submission_id', 'hidden', array(
                'name' => 'submission_id'
            ));
        }

        $fieldset->addField('name', 'text', array(
            'name' => 'name',
            'label' => Mage::helper('SoftUni_KristinaKovacheva')->__('Name'),
            'title' => Mage::helper('SoftUni_KristinaKovacheva')->__('Name'),
            'required' => true
        ));

        $fieldset->addField('phone', 'text', array(
            'name' => 'phone',
            'label' => Mage::helper('SoftUni_KristinaKovacheva')->__('Phone'),
            'title' => Mage::helper('SoftUni_KristinaKovacheva')->__('Phone'),
            'required' => true
        ));
        $fieldset->addField('age', 'text', array(
            'name' => 'age',
            'label' => Mage::helper('SoftUni_KristinaKovacheva')->__('Age'),
            'title' => Mage::helper('SoftUni_KristinaKovacheva')->__('Age'),
            'required' => true
        ));
        $fieldset->addField('email', 'text', array(
            'name' => 'email',
            'label' => Mage::helper('SoftUni_KristinaKovacheva')->__('Email'),
            'title' => Mage::helper('SoftUni_KristinaKovacheva')->__('Email'),
            'required' => true
        ));

        $form->setValues($model->getData());
//        var_dump($model->getData());die;
        $form->setUseContainer(true);
        $this->setForm($form);

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}