<?php

class Naya_FacebookComments_Model_Languages
{
    public function toOptionArray()
    {
        $options = array(
            array('value'=>'af_ZA','label'=> Mage::helper('naya_facebookcomments')->__('Afrikaans')),
            array('value'=>'sq_AL','label'=> Mage::helper('naya_facebookcomments')->__('Albanian')),
            array('value'=>'ar_AR','label'=> Mage::helper('naya_facebookcomments')->__('Arabic')),
            array('value'=>'hy_AM','label'=> Mage::helper('naya_facebookcomments')->__('Armenian')),
            array('value'=>'az_AZ','label'=> Mage::helper('naya_facebookcomments')->__('Azerbaijani')),
            array('value'=>'eu_ES','label'=> Mage::helper('naya_facebookcomments')->__('Basque')),
            array('value'=>'be_BY','label'=> Mage::helper('naya_facebookcomments')->__('Belarusian')),
            array('value'=>'bn_IN','label'=> Mage::helper('naya_facebookcomments')->__('Bengali')),
            array('value'=>'bs_BA','label'=> Mage::helper('naya_facebookcomments')->__('Bosnian')),
            array('value'=>'bg_BG','label'=> Mage::helper('naya_facebookcomments')->__('Bulgarian')),
            array('value'=>'ca_ES','label'=> Mage::helper('naya_facebookcomments')->__('Catalan')),
            array('value'=>'cx_PH','label'=> Mage::helper('naya_facebookcomments')->__('Cebuano')),
            array('value'=>'hr_HR','label'=> Mage::helper('naya_facebookcomments')->__('Croatian')),
            array('value'=>'cs_CZ','label'=> Mage::helper('naya_facebookcomments')->__('Czech')),
            array('value'=>'da_DK','label'=> Mage::helper('naya_facebookcomments')->__('Danish')),
            array('value'=>'nl_NL','label'=> Mage::helper('naya_facebookcomments')->__('Dutch')),
            array('value'=>'en_PI','label'=> Mage::helper('naya_facebookcomments')->__('English (Pirate)')),
            array('value'=>'en_GB','label'=> Mage::helper('naya_facebookcomments')->__('English (UK)')),
            array('value'=>'en_US','label'=> Mage::helper('naya_facebookcomments')->__('English (US)')),
            array('value'=>'en_UD','label'=> Mage::helper('naya_facebookcomments')->__('English (Upside Down)')),
            array('value'=>'eo_EO','label'=> Mage::helper('naya_facebookcomments')->__('Esperanto')),
            array('value'=>'et_EE','label'=> Mage::helper('naya_facebookcomments')->__('Estonian')),
            array('value'=>'fo_FO','label'=> Mage::helper('naya_facebookcomments')->__('Faroese')),
            array('value'=>'tl_PH','label'=> Mage::helper('naya_facebookcomments')->__('Filipino')),
            array('value'=>'fi_FI','label'=> Mage::helper('naya_facebookcomments')->__('Finnish')),
            array('value'=>'fr_CA','label'=> Mage::helper('naya_facebookcomments')->__('French (Canada)')),
            array('value'=>'fr_FR','label'=> Mage::helper('naya_facebookcomments')->__('French (France)')),
            array('value'=>'fy_NL','label'=> Mage::helper('naya_facebookcomments')->__('Frisian')),
            array('value'=>'gl_ES','label'=> Mage::helper('naya_facebookcomments')->__('Galician')),
            array('value'=>'ka_GE','label'=> Mage::helper('naya_facebookcomments')->__('Georgian')),
            array('value'=>'de_DE','label'=> Mage::helper('naya_facebookcomments')->__('German')),
            array('value'=>'el_GR','label'=> Mage::helper('naya_facebookcomments')->__('Greek')),
            array('value'=>'gn_PY','label'=> Mage::helper('naya_facebookcomments')->__('Guarani')),
            array('value'=>'he_IL','label'=> Mage::helper('naya_facebookcomments')->__('Hebrew')),
            array('value'=>'hi_IN','label'=> Mage::helper('naya_facebookcomments')->__('Hindi')),
            array('value'=>'hu_HU','label'=> Mage::helper('naya_facebookcomments')->__('Hungarian')),
            array('value'=>'is_IS','label'=> Mage::helper('naya_facebookcomments')->__('Icelandic')),
            array('value'=>'id_ID','label'=> Mage::helper('naya_facebookcomments')->__('Indonesian')),
            array('value'=>'ga_IE','label'=> Mage::helper('naya_facebookcomments')->__('Irish')),
            array('value'=>'it_IT','label'=> Mage::helper('naya_facebookcomments')->__('Italian')),
            array('value'=>'ja_JP','label'=> Mage::helper('naya_facebookcomments')->__('Japanese')),
            array('value'=>'jv_ID','label'=> Mage::helper('naya_facebookcomments')->__('Javanese')),
            array('value'=>'kn_IN','label'=> Mage::helper('naya_facebookcomments')->__('Kannada')),
            array('value'=>'km_KH','label'=> Mage::helper('naya_facebookcomments')->__('Khmer')),
            array('value'=>'ko_KR','label'=> Mage::helper('naya_facebookcomments')->__('Korean')),
            array('value'=>'ku_TR','label'=> Mage::helper('naya_facebookcomments')->__('Kurdish')),
            array('value'=>'la_VA','label'=> Mage::helper('naya_facebookcomments')->__('Latin')),
            array('value'=>'lv_LV','label'=> Mage::helper('naya_facebookcomments')->__('Latvian')),
            array('value'=>'fb_LT','label'=> Mage::helper('naya_facebookcomments')->__('Leet Speak')),
            array('value'=>'lt_LT','label'=> Mage::helper('naya_facebookcomments')->__('Lithuanian')),
            array('value'=>'mk_MK','label'=> Mage::helper('naya_facebookcomments')->__('Macedonian')),
            array('value'=>'ms_MY','label'=> Mage::helper('naya_facebookcomments')->__('Malay')),
            array('value'=>'ml_IN','label'=> Mage::helper('naya_facebookcomments')->__('Malayalam')),
            array('value'=>'ne_NP','label'=> Mage::helper('naya_facebookcomments')->__('Nepali')),
            array('value'=>'nb_NO','label'=> Mage::helper('naya_facebookcomments')->__('Norwegian (bokmal)')),
            array('value'=>'nn_NO','label'=> Mage::helper('naya_facebookcomments')->__('Norwegian (nynorsk)')),
            array('value'=>'ps_AF','label'=> Mage::helper('naya_facebookcomments')->__('Pashto')),
            array('value'=>'fa_IR','label'=> Mage::helper('naya_facebookcomments')->__('Persian')),
            array('value'=>'pl_PL','label'=> Mage::helper('naya_facebookcomments')->__('Polish')),
            array('value'=>'pt_BR','label'=> Mage::helper('naya_facebookcomments')->__('Portuguese (Brazil)')),
            array('value'=>'pt_PT','label'=> Mage::helper('naya_facebookcomments')->__('Portuguese (Portugal)')),
            array('value'=>'pa_IN','label'=> Mage::helper('naya_facebookcomments')->__('Punjabi')),
            array('value'=>'ro_RO','label'=> Mage::helper('naya_facebookcomments')->__('Romanian')),
            array('value'=>'ru_RU','label'=> Mage::helper('naya_facebookcomments')->__('Russian')),
            array('value'=>'sr_RS','label'=> Mage::helper('naya_facebookcomments')->__('Serbian')),
            array('value'=>'zh_CN','label'=> Mage::helper('naya_facebookcomments')->__('Simplified Chinese (China)')),
            array('value'=>'si_LK','label'=> Mage::helper('naya_facebookcomments')->__('Sinhala')),
            array('value'=>'sk_SK','label'=> Mage::helper('naya_facebookcomments')->__('Slovak')),
            array('value'=>'sl_SI','label'=> Mage::helper('naya_facebookcomments')->__('Slovenian')),
            array('value'=>'es_LA','label'=> Mage::helper('naya_facebookcomments')->__('Spanish')),
            array('value'=>'es_ES','label'=> Mage::helper('naya_facebookcomments')->__('Spanish (Spain)')),
            array('value'=>'sw_KE','label'=> Mage::helper('naya_facebookcomments')->__('Swahili')),
            array('value'=>'sv_SE','label'=> Mage::helper('naya_facebookcomments')->__('Swedish')),
            array('value'=>'ta_IN','label'=> Mage::helper('naya_facebookcomments')->__('Tamil')),
            array('value'=>'te_IN','label'=> Mage::helper('naya_facebookcomments')->__('Telugu')),
            array('value'=>'th_TH','label'=> Mage::helper('naya_facebookcomments')->__('Thai')),
            array('value'=>'zh_HK','label'=> Mage::helper('naya_facebookcomments')->__('Traditional Chinese (Hong Kong)')),
            array('value'=>'zh_TW','label'=> Mage::helper('naya_facebookcomments')->__('Traditional Chinese (Taiwan)')),
            array('value'=>'tr_TR','label'=> Mage::helper('naya_facebookcomments')->__('Turkish')),
            array('value'=>'uk_UA','label'=> Mage::helper('naya_facebookcomments')->__('Ukrainian')),
            array('value'=>'ur_PK','label'=> Mage::helper('naya_facebookcomments')->__('Urdu')),
            array('value'=>'vi_VN','label'=> Mage::helper('naya_facebookcomments')->__('Vietnamese')),
            array('value'=>'cy_GB','label'=> Mage::helper('naya_facebookcomments')->__('Welsh'))
        );
        return $options;
    }
}