<h2><?php echo $this->__('Comments') ?></h2>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/<?php echo (string)$this->getLanguage(); ?>/sdk.js#xfbml=1<?php echo (string)$this->getAppId(); ?>&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-comments" data-href="<?php echo $this->getProductUrl(); ?>" data-numposts="<?php echo (int)$this->getNumOfComments(); ?>" data-colorscheme="light" data-width="100%"></div>
