
<h3>
    <?php echo $this->escapeHtml($this->getTitle()) ?>
</h3>

<?php
    $productCollection = $this->getProductCollection();
?>

<ul>

    <?php foreach($productCollection as $product): ?>

        <li>
            <a href="<?php echo $product->getProductUrl() ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(135); ?>"
                     alt="<?php echo $this->stripTags($product->getName()) ?>"
                />
                <?php echo $this->escapeHtml($product->getName()) ?>
            </a>
        </li>


    <?php endforeach; ?>
</ul>
