<?php
/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<div class="pay-with-amazon-onepage-shortcut">
    <h3><?php echo $this->__('Amazon Pay'); ?></h3>
    <?php if ($this->isVirtual()): ?>
        <p><?php echo $this->__('<strong>Amazon Pay</strong> helps you shop quickly, safely and securely. You can pay on our website without re-entering your payment and address details.'); ?></p>
    <?php else: ?>
        <p><?php echo $this->__('<strong>Amazon Pay</strong> helps you shop quickly, safely and securely. You can pay on our website without re-entering your payment and address details. All Amazon transactions are protected by Amazon&apos;s A-to-z Guarantee.'); ?></p>
    <?php endif; ?>
    <div id="<?php echo $this->getWidgetHtmlId(); ?>" class="<?php echo $this->getWidgetClass(); ?>">
        <?php if ($buttonImgUrl = $this->getButtonWidgetUrl()): ?>
            <img src="<?php echo $buttonImgUrl; ?>"/>
        <?php endif; ?>
    </div>
    <?php if ($this->isCustomDesignSet()): ?>
        <script type="text/javascript">//<![CDATA[
            var buttonDiv = $('<?php echo $this->getWidgetHtmlId(); ?>');
            <?php if ($buttonType = $this->getButtonType()): ?>
                buttonDiv.buttonType = '<?php echo $buttonType; ?>';
            <?php endif; ?>
            <?php if ($buttonSize = $this->getButtonSize()): ?>
                buttonDiv.buttonSize = '<?php echo $buttonSize; ?>';
            <?php endif; ?>
            <?php if ($buttonColor = $this->getButtonColor()): ?>
                buttonDiv.buttonColor = '<?php echo $buttonColor; ?>';
            <?php endif; ?>
        //]]></script>
    <?php endif; ?>
</div>
