<form action="<?php echo $this->getActionUrl(); ?>" method="post">
    <label><?php echo Mage::helper('softuni_ventsyslavvassilev')->__('Name'); ?>: </label><br><input type="text" name="Name"><br><br>
    <label>Phone: </label><br><input type="text" name="Phone"><br><br>
    <label>Age: </label><br><input type="text" name="Age"><br><br>
    <label>Email: </label><br><input type="text" name="Email"><br><br>
    <button><?php echo Mage::helper('softuni_ventsyslavvassilev')->__('Submit'); ?></button>
</form>

