<form action="<?php echo $this->getUrl('softuni_ventsyslavvassilev/form/persist'); ?>" method="post">
    <label>Name: </label><br><input type="text" name="Name"><br><br>
    <label>Phone: </label><br><input type="text" name="Phone"><br><br>
    <label>Age: </label><br><input type="text" name="Age"><br><br>
    <label>Email: </label><br><input type="text" name="Email"><br><br>
    <button>Submit</button>
</form>

