<form action="<?php echo $this->getActionUrl(); ?>" method="POST">
    <div>
        <label for=""><?php echo Mage::helper('SoftUni_KristinaKovacheva')->__('Name')?> :</label>
        <input type="text" name="name"/>
    </div>
    <div>
        <label for=""><?php echo Mage::helper('SoftUni_KristinaKovacheva')->__('Phone')?> :</label>
        <input type="text" name="phone"/>
    </div>
    <div>
        <label for=""><?php echo Mage::helper('SoftUni_KristinaKovacheva')->__('Age')?> :</label>
        <input type="text" name="age"/>
    </div>
    <div>
        <label for=""><?php echo Mage::helper('SoftUni_KristinaKovacheva')->__('Email')?> :</label>
        <input type="text" name="email"/>
    </div>
    <button><?php echo Mage::helper('SoftUni_KristinaKovacheva')->__('Submit') ?></button>
</form>