<form action="<?php echo $this->getUrl('softuni_kristinakovacheva/form/post') ?>" method="POST">
    <div>
        <label for="">Name:</label>
        <input type="text" name="name"/>
    </div>
    <div>
        <label for="">Phone:</label>
        <input type="text" name="phone"/>
    </div>
    <div>
        <label for="">Age:</label>
        <input type="text" name="age"/>
    </div>
    <div>
        <label for="">Email:</label>
        <input type="text" name="email"/>
    </div>
    <button>Submit</button>
</form>