<h3><?php echo $this->escapeHtml($this->getTitle()); ?></h3>

<?php
$productCollection = $this->getProductCollection();
?>
<ul>
    <?php foreach ($productCollection as $product) : ?>
    <li>
        <a href="<?php echo $product->getProductUrl(); ?>">
            <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" />
            <?php echo $this->escapeHtml($product->getName()); ?>
        </a>
    </li>

    <?php endforeach; ?>
</ul>